#!/bin/bash

# Check Node.js version
node_version=$(node -v)
if [[ $node_version != v16.* ]]; then
  echo "WARNING: not running with recommended Node version (v16)"
fi

# Install packages defined in package.json
npm install

# Check if .dev.vars exists
if [ ! -f ".dev.vars" ]; then
  echo "ERROR: .dev.vars not found."
  exit 1
fi

# Check if ngrok is installed
if ! command -v ngrok &> /dev/null; then
  echo "ERROR: ngrok is not installed."
  exit 1
fi

# Open new terminal and run ngrok
# Edit this line if your terminal is not GNOME-based
gnome-terminal -- ngrok http 8787

# Start project
wrangler dev
