#!/bin/bash

# Check Node.js version
node_version=$(node -v)
if [[ $node_version != v16.* ]]; then
  echo "Node.js version must be v16.16.0 or higher."
  exit 1
fi

# Install packages defined in package.json
npm install

# Check if .dev.vars exists
if [ ! -f ".dev.vars" ]; then
  echo ".dev.vars not found."
  exit 1
fi

# Check if ngrok is installed
if ! command -v ngrok &> /dev/null; then
  echo "Ngrok is not installed."
  exit 1
fi

# Build project
node src/build.js

# Start project
wrangler dev

# Open new terminal and run ngrok
# Edit this line if your terminal is not GNOME-based
gnome-terminal -- ngrok http 8787
