name = "[the name of your Cloudflare Worker]"
# don't touch anything here!
main = "./dist/main.js"
compatibility_date = "2023-10-22"
node_compat = true

# d1 configurations
[[d1_databases]]
binding = "database"
database_name = "[the name of your binded D1 Database]"
database_id = "[your D1 database ID]"

# cron triggers - don't edit this unless you add another job
[triggers]
crons = ["0 */6 * * *", "0 */1 * * *"]

[vars]
# put your variables here
# as stated, it is in the format of KEY = "value"
# each key must be in their own line